### ISSUE TITLE
cannot install on npm

### ISSUE THREAD

**Issue by Symboler** [chicoxyzzy/node-releases#10] opened 2019-05-24 04:59 UTC
![image](https://user-images.githubusercontent.com/33592051/58303597-7e558600-7e23-11e9-933c-d722e7f532a4.png)
npm install --save node-releases ,then throw the error

**Comment by laomu1988** [comment] 2019-05-24 05:05
fail when use `npm install node-releases@1.1.21`
success when use `npm install node-releases@1.1.20`

**Comment by chicoxyzzy** [comment] 2019-07-22 16:48
Sorry for long response. Do you have any issues with latest published versions?

**Comment by chicoxyzzy** [comment] 2019-09-09 13:33
It seems that everything works now. I'll close this issue. Feel free to reopen if you think the issue is not solved.

**Closed by chicoxyzzy** 2019-09-09 13:33 UTC
